---
format: revealjs
bibliography: references.bib
title: "Research on the programme"
subtitle: DClin Research Methods 1
author: Dr Christopher Wilson
institute: Teesside University

logo: "logo.jpg"
csl: apa.csl
---

## Overview

- Thesis timeline
- Some thoughts on project development

# Thesis timeline

```{mermaid}
gantt
    title Thesis Timeline (proposal development)
    dateFormat  YYYY-MM
    section Thesis
    axisFormat %m/%y
    Project Consideration : 2023-11-24, 2024-01
    Project List Goes Live :milestone, 2023-11, 0d
    Teaching Session :milestone, 2023-11, 0d
    Trainees Select Project :milestone, 2024-01, 0d
    Proposal Development : 2024-01,2024-05
    Proposal Submission :milestone, 2024-05, 0d

```

Note: The exact dates of submission are on Blackboard.

# Thesis development

## Building a rationale from the literature

- Regardless of the source of your thesis project idea, you will need to develop a thorough rationale for your project, based on the literature.

- This is a fundamental part of the thesis development process.

- In this sense, consider reviewing the literature as an active process, rather than a passive one.

> The biggest question is: "Why is this project important and what does it add?"

## Research doesn't happen in big chunks of time

- Research is a process that happens with ongoing engagement.

- Conceptual connections between theories, frameworks, and ideas are made over time.

- Engage with your supervisor regularly, and make notes of how your ideas develop and change over time.

> You should always know what you are working towards. If not, meet with your supervisor.

## Use tools to help you

Tools for storing and organising your research (choose one):

- Zotero
- Mendeley
- Papers
- Paperpile

They are more than just reference managers:

- They can help you organise your research
- They can help you develop your ideas
- They can help you speed up the writing process